{"name": "Invalid login attempt to the portal [test_user@mitigram.com-testing@123-Invalid login attempt.]", "status": "passed", "steps": [{"name": "Given User is on the application home page", "status": "passed", "start": 1713533562514, "stop": 1713533565210}, {"name": "When User performs login with \"test_user@mitigram.com\" and \"testing@123\"", "status": "passed", "start": 1713533565210, "stop": 1713533566606}, {"name": "Then Login attempt should fail with the message \"Invalid login attempt.\"", "status": "passed", "start": 1713533566606, "stop": 1713533566749}], "attachments": [{"name": "screenshot: Invalid login attempt to the portal", "source": "f75b98db-0a49-402f-ba28-874daf608222-attachment.png", "type": "image/png"}], "parameters": [{"name": "user_name", "value": "test_user@mitigram.com"}, {"name": "password", "value": "testing@123"}, {"name": "notification", "value": "Invalid login attempt."}], "start": 1713533562514, "stop": 1713533566749, "uuid": "196c86e6-c2cc-9a15-6d3a-eb236590a186", "historyId": "196c86e6c2cc9a156d3aeb236590a186", "fullName": "features\\mitigram_tests.feature:Invalid login attempt to the portal", "labels": [{"name": "host", "value": "DESKTOP-4KIF8N0"}, {"name": "thread", "value": "29196-MainThread"}, {"name": "framework", "value": "pytest-bdd"}, {"name": "language", "value": "cpython3"}, {"name": "feature", "value": "Test login to mitigram portal"}]}